AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-splitter-backend
  
  Serverless backend for the Expense Splitter application.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  ##########################################################################
  #   DynamoDB Table                                                       #
  ##########################################################################
  ExpenseSplitterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-ExpenseTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  ##########################################################################
  #   Cognito User Pool                                                    #
  ##########################################################################
  ExpenseSplitterUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  ExpenseSplitterUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}-WebClient
      UserPoolId: !Ref ExpenseSplitterUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  ##########################################################################
  #   Lambda Functions                                                     #
  ##########################################################################
  CreateGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create-group/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpenseSplitterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseSplitterTable
      Events:
        CreateGroup:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseSplitterApi
            Path: /groups
            Method: post

  AddExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/add-expense/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpenseSplitterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseSplitterTable
      Events:
        AddExpense:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseSplitterApi
            Path: /expenses
            Method: post

  GetSettlementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-settlements/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpenseSplitterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseSplitterTable
      Events:
        GetSettlements:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseSplitterApi
            Path: /groups/{groupId}/settlements
            Method: get

  GetUserGroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-user-groups/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpenseSplitterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseSplitterTable
      Events:
        GetUserGroups:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseSplitterApi
            Path: /groups
            Method: get

  GetGroupExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-group-expenses/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpenseSplitterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseSplitterTable
      Events:
        GetGroupExpenses:
          Type: Api
          Properties:
            RestApiId: !Ref ExpenseSplitterApi
            Path: /groups/{groupId}/expenses
            Method: get

  ##########################################################################
  #   API Gateway                                                          #
  ##########################################################################
  ExpenseSplitterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt ExpenseSplitterUserPool.Arn

  ##########################################################################
  #   Static Site Hosting                                                  #
  ##########################################################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-frontend
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub ${FrontendBucket.Arn}/*

##########################################################################
#   Outputs                                                              #
##########################################################################
Outputs:
  Region:
    Description: "Region"
    Value: !Ref "AWS::Region"
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref ExpenseSplitterUserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref ExpenseSplitterUserPoolClient
  TableName:
    Description: "DynamoDB Table Name"
    Value: !Ref ExpenseSplitterTable
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ExpenseSplitterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FrontendBucketName:
    Description: "S3 Bucket for Frontend Hosting"
    Value: !Ref FrontendBucket
  WebsiteURL:
    Description: "URL for website hosted on S3"
    Value: !GetAtt FrontendBucket.WebsiteURL
